Support Celo bridge assets
Uniswap/token-list-bridge-utils pull request #49
Opened 2023-08-11 00:41 UTC by Jesse-Sawa

Will create follow up PR to add further address mappings

2023-08-30 08:18 UTC, nicolasbrugneaux requested changes

2023-08-30 08:18 UTC, nicolasbrugneaux commented on src/constants/tokens.ts
> +  'Teather USD'
```suggestion
  'Tether USD'
```

2023-08-30 08:18 UTC, nicolasbrugneaux commented on src/index.test.ts
> +  console.log(tokenList )
```suggestion
  expect(tokenList).toBeDefined()
  expect(tokenList?.version).toEqual(celoedSampleTokenList.version)
```

removed console logs

2023-08-30 08:18 UTC, nicolasbrugneaux commented on src/providers/CeloMappingProvider.ts
> +// barring a better external source, we use a local source of mappings for avalanche
comment seems unrelated
```suggestion
// barring a better external source, we use a local source of mappings for celo
```

2023-09-05 17:25 UTC, JFrankfurt commented on src/fixtures/index.ts
> +//todo check if this is needed
```suggestion

```

2023-09-05 17:26 UTC, just-toby approved these changes
please fix the formatting and comment

2023-09-05 17:26 UTC, just-toby commented on src/fixtures/index.ts
> +//todo check if this is needed
please remove this comment

2023-09-05 17:26 UTC, just-toby commented on src/index.test.ts
> +  baseSampleTokenList_3, celoedSampleTokenList,
can you fix the formatting here?

2023-09-05 18:26 UTC, Jesse-Sawa commented on src/index.test.ts
> +  baseSampleTokenList_3, celoedSampleTokenList,
Done!

2023-09-06 15:03 UTC, JFrankfurt approved these changes

2023-09-14 19:30 UTC, merged